name: Bug Report
description: You have an issue with the UAD-ng software itself
title: "bug(scope): "
labels: ["bug"]
body:
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to fill out this bug report!
- type: textarea
  id: what-happened
  attributes:
    label: Describe the bug
    description: A clear and concise description of what the bug is, and how to reproduce it
  validations:
    required: true
- type: textarea
  id: expected-behavior
  attributes:
    label: Expected behavior
    description: A clear and concise description of what you expected to happen.
  validations:
    required: true
- type: textarea
  id: suggested-solution
  attributes:
    label: You have a solution?
    description: What to do to fix the issue.
- type: dropdown
  id: os
  attributes:
    label: Operating System
    options:
      - Linux
      - MacOS
      - Windows
  validations:
    required: true
- type: input
  id: wm
  attributes:
    label: Window Manager
    description: Please, fill it if OS is Linux
    placeholder: Wayland, xorg, etc...
- type: input
  id: de
  attributes:
    label: Desktop Environment
    description: Please, fill it if OS is Linux
    placeholder: GNOME 46, KDE Plasma 4, etc...
- type: textarea
  id: logfiles
  attributes:
    label: Provide logs
    description: Upload the logfile generated by UAD-ng. See https://github.com/Universal-Debloater-Alliance/universal-android-debloater-next-generation/wiki/FAQ#where-are-the-logfiles for the location of logfiles.
  validations:
    required: true

- type: checkboxes
  id: acknowledgements
  attributes:
    label: Acknowledgements
    description: Your bug report will be closed if you don't follow the checklist below.
    options:
      - label: This issue is not a duplicate of an existing bug report.
        required: true
      - label: I have chosen an appropriate title.
        required: true
      - label: All requested information has been provided properly.
        required: true
